# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_auto_20170905_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
